development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://nzwfcvvcsrybus:e7e31a2ee70a8ec63f3585e89aa9688fc63fae277df2c507c7755258f546f643@ec2-50-19-95-47.compute-1.amazonaws.com:5432/dckqp6od84lic8

