# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Product.destroy_all
Product.create(:name => "Osprey Atmos 65 AG Pack", :description => " The foundation of the Osprey Atmos AG™ 65 is Osprey’s Anti-Gravity™ suspension system that delivers outstanding ventilation and carrying comfort. This award winning pack has earned a solid reputation with savvy thru-hikers on the Pacific Crest Trail. ", :image_url => "https://www.ospreypacks.com/images/product/series/features/Aura_S15_Detail_StowOnTheGo-min.jpg", :color => "Greenish Blue ", :price => "$346.00 ")
Product.create(:name => "Mountain Hardwear Hydra Pro Glove ", :description => " Fabric Body: 4-Way Stretch Nylon Softshell Body Fabric Content: 92% nylon, 8% elastane Insulation: Thermal.Q™ 120g Fabric Palm: Water-resistant Goatskin Leather Fabric Laminate: OutDry® Waterproof Technology", :image_url => "http://s7d5.scene7.com/is/image/ColumbiaSportswear2/OM5422_010_f ", :color => " greyish black", :price => "$64.98 ")
Product.create(:name => "Vasque Skywalk GTX ", :description => "DBack by popular demand! Don’t let the retro styling of the original fool you, this is an incredibly capable, surprisingly nimble and award-winning trail traveler and most likely your new favorite boot.", :image_url => "http://a1.zassets.com/images/z/3/3/8/7/4/9/3387499-p-MULTIVIEW.jpg", :color => "olive brown ", :price => " $199.99")
Product.create(:name => "MSR Hubba Hubba NX 2-Person Tent ", :description => "20-denier ripstop nylon / 15-denier nylon mesh Minimum weight is 1.54 kg/3 lb. 7 oz.; two Fast & Light options from .97 kg/2 lb. 2 oz. Head and elbow room throughout tent; two large side-entry vestibules to store gear Two large StayDry doors with built-in rain gutters; adaptable, cross-ventilating rainfly Unified hub-and-pole system with color-coded clips; ultra-compact compression stuff sack ", :image_url => "https://static1.squarespace.com/static/5346a846e4b0101b157468cf/5554fe12e4b077499cda64a6/55550063e4b0f031496a1aa2/1431634385873/Hubba+Hubba.jpg ", :color => "red and white ", :price => " $290.19")